### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by CrimChin** [iTCf/mikulan_et_al_2020#1]
Hello, I was trying to run through your code and noticed that in PreProcess.py, and Source_Loc.py some modules were missing. Info and itcfpy were the ones I couldn't find. Are those the sensitive files that couldn't be shared or am I not looking in the right places?

**Comment by ezemikulan** [comment]
Hi, yes, those are the modules that contain sensitive information. The _preprocess.py_ code shouldn't be necessary as the data that we shared is already pre-processed. Regarding the functions from _itcfpy_ that _source_loc.py_ uses, I have added them to the _fx_source_loc.py_ file, so you can change the import line to load it from there and it should work.
