### ISSUE TITLE
Pickle Error loading the *.npy data

### ISSUE THREAD

**Issue by martinwimpff** [iTCf/mikulan_et_al_2020#2]
I downloaded the dataset and tried to run the [`_00_getting_started.ipynb`](https://github.com/iTCf/mikulan_et_al_2020/blob/master/_00_getting_started.ipynb) script.
I get an error while trying to load the *.npy files via [`load_bids()`](https://github.com/iTCf/mikulan_et_al_2020/blob/1bfed2384b523c8ffcc98b09faad3e94b3e0b138/fx_bids.py#L234)
If I use [`data = np.load(fname_eeg)`](https://github.com/iTCf/mikulan_et_al_2020/blob/1bfed2384b523c8ffcc98b09faad3e94b3e0b138/fx_bids.py#L254) I get the error:
ValueError: Cannot load file containing pickled data when allow_pickle=False
If I set `allow_pickle=True` I get the error:
_pickle.UnpicklingError: Failed to interpret file '...' as a pickle

This [thread](https://stackoverflow.com/questions/60191681/cannot-load-file-containing-pickled-data-python-npy-i-o) suggests that the file is corrupted.

Any ideas?

**Comment by ezemikulan** [comment]
Hi, I don't think the file is corrupted as many people have used it without problems and I've just re-checked and I can read the files as usual. 

It looks like the filename is not correct as it says _"Failed to interpret file '...' as a pickle"_. The file shouldn't be _'...'_. Can you paste a reproducible example?

It should load If you do this in the folder where the file is:

```python
import numpy as np
data = np.load('sub-01_task-seegstim_run-01_epochs.npy')
```

**Comment by martinwimpff** [comment]
Hi, thanks for the fast response!

The link is not the problem, I just inserted those ... to avoid pasting an unecessary long path.
A very minimal example can be found [here](https://colab.research.google.com/drive/17Rmbu0VkfOfLhGP3Dujnmd7-2uLoQ4VT?usp=sharing).

I downloaded the data as a zip file, extracted it and then uploaded the file to colab.

**Comment by ezemikulan** [comment]
Thanks, then it looks like a file corruption during transfer to me. Also, are you using the latest version of the dataset? 

Please re-download it from here: https://gin.g-node.org/ezemikulan/Localize-MI and try again.

You can download only one file if you prefer: 

https://gin.g-node.org/ezemikulan/Localize-MI/src/master/derivatives/epochs/sub-07/eeg/sub-07_task-seegstim_run-07_epochs.npy

**Comment by martinwimpff** [comment]
Sorry, i didn't read this "Annexed files (by default, files larger than 10 MB) will be included as pointer files (stubs) but the data will not be included. To get the content of the big files you need to download them individually from this web page."
Just wasn't familiar with the workflow.
Thanks for your help!
